---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.8 enthält mehrere neue Funktionen und Verbesserungen. 
---
= Was ist neu in Cloud Volumes ONTAP 9.8
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.8 enthält mehrere neue Funktionen und Verbesserungen.

Zusätzliche Funktionen und Erweiterungen sind ebenfalls in den neuesten Versionen von BlueXP verfügbar. Siehe https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Versionshinweise zu BlueXP"^] Entsprechende Details.



== 9.8 GA (5. Januar 2021)

Das Release von Cloud Volumes ONTAP 9.8 (General Availability, GA) ist jetzt verfügbar. Die GA-Version enthält Bug Fixes. BlueXP fordert Sie auf, die vorhandenen 9.8 RC1- und 9.7-Systeme auf diese Version zu aktualisieren.



== Änderungen mit Connector 3.9.2 (4. Januar 2021)

Die Version 3.9.2 des BlueXP Connectors enthält verschiedene Verbesserungen für Cloud Volumes ONTAP, darunter die Unterstützung von AWS Outposts, größere Festplatten in der Google Cloud und mehr.

Wechseln Sie zum https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Versionshinweise zu BlueXP"^] Weitere Informationen zur Version 3.9.2.



== E48s_v3 jetzt mit HA-Paaren unterstützt (21. Dezember 2020)

Der VM-Typ E48s_v3 wird nun mit Cloud Volumes ONTAP HA-Paaren in Microsoft Azure unterstützt.



== Unterstützte EC2-Instanzen (11. Dezember 2020)

Ab den Instanztypen 9.8 Release, c4, m4 und r4 EC2 werden nicht mit neuen Cloud Volumes ONTAP Systemen unterstützt. Das Ändern eines vorhandenen 9.8 Systems auf einen dieser Instanztypen wird auch nicht unterstützt.

Wenn Sie ein Cloud Volumes ONTAP 9.7-System besitzen, das auf einem Instanztyp c4, m4 oder r4 ausgeführt wird, können Sie weiterhin ein Upgrade auf Version 9.8 durchführen.



== Update zu 9.8 RC1 (12. November 2020)

Ähnlich wie bei Systemen mit einzelnen Nodes weist BlueXP nun neuen 9.8 HA-Paar-Implementierungen in AWS eine Core-Festplatte zu, wenn Sie einen Instanztyp C5, M5 oder R5 verwenden. Die Kernfestplatte bietet mehr Möglichkeiten, zwischen unterstützten Instanztypen zu wechseln, erweitert die Fähigkeit des Systems, Kerndateien bei Problemen zu sammeln, und unterstützt künftig größere Instanztypen.

Die Core-Festplatte ist eine General Purpose SSD (gp2) mit 540 gib.


NOTE: Zusätzlich zu diesem zentralen Datenträger wird nun eine weniger Datenfestplatte auf Systemen unterstützt, die diese Instanztypen nutzen. link:reference-limits-aws.html["Erfahren Sie mehr über Storage-Limits in AWS"].



== 9.8 RC1 (8. November 2020)

Cloud Volumes ONTAP 9.8 RC1 ist jetzt auf der AWS, Azure und Google Cloud Platform verfügbar. In Azure ist 9.8 RC1 nur derzeit für Upgrades verfügbar.

Zusätzlich zu den bereits mit eingeführten Funktionen https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9.8"^], Diese Version von Cloud Volumes ONTAP enthält die folgenden:

* <<Hochverfügbarkeitspaare in Google Cloud>>
* <<Fixes für Azure NIC trennen Ereignisse und Wartungsereignisse>>
* <<Hohe Schreibgeschwindigkeit mit HA-Paaren in AWS und Azure>>
* <<Unterstützung von bis zu 24 Storage VMs in AWS>>
* <<Zentrale Festplatte für Single-Node-Systeme in AWS>>




=== Hochverfügbarkeitspaare in Google Cloud

Cloud Volumes ONTAP HA-Paare sind nun in Google Cloud verfügbar.

Ein HA-Paar bietet Zuverlässigkeit der Enterprise-Klasse und unterbrechungsfreien Betrieb bei Ausfällen in der Cloud-Umgebung. Ähnlich wie Cloud Volumes ONTAP in AWS umfasst ein HA-Paar in Google Cloud zwei Cloud Volumes ONTAP Nodes, deren Daten synchron gespiegelt wurden. Außerdem ist eine Instanz des Mediators erforderlich, die einen Kommunikationskanal zur Unterstützung bei Storage-Übernahme und -Rückgabe bietet.

Anzeigen link:reference-configs-gcp.html["Unterstützte Konfigurationen"] Und link:reference-limits-gcp.html["Storage-Beschränkungen"].

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-google-cloud.html["Erfahren Sie mehr über HA-Paare in Google Cloud"^].



=== Fixes für Azure NIC trennen Ereignisse und Wartungsereignisse

Diese Version bietet verschiedene Verbesserungen für den Umgang mit Frostereignissen bei Cloud Volumes ONTAP, das Abtrennen von Azure NIC-Ereignissen und andere Azure-Wartungsaktivitäten (beispielsweise beim Widerruf virtueller Funktionen). Cloud Volumes ONTAP ist in diesem Release fehlertoleranter und kann Azure Ereignisse leichter verarbeiten. Die Wahrscheinlichkeit von Serviceunterbrechungen oder Cluster-Verschlechterung ist daher geringer.



=== Hohe Schreibgeschwindigkeit mit HA-Paaren in AWS und Azure

Cloud Volumes ONTAP unterstützt jetzt bei Verwendung einer bestimmten Instanz oder eines VM-Typs eine hohe Schreibgeschwindigkeit mit HA-Paaren in AWS und Azure. Hohe Schreibgeschwindigkeit ist eine gute Wahl, wenn für Ihre Workload eine schnelle Schreibleistung erforderlich ist und Sie das Risiko eines Datenverlusts bei einem ungeplanten Systemausfall überstehen können.

Bevor Sie eine Schreibgeschwindigkeit auswählen, sollten Sie die Unterschiede zwischen den normalen und den hohen Einstellungen sowie die Risiken und Empfehlungen bei hoher Schreibgeschwindigkeit verstehen.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Weitere Informationen ."^].



=== Unterstützung von bis zu 24 Storage VMs in AWS

Bis zu 24 Storage VMs werden mit Cloud Volumes ONTAP nun auch in AWS unterstützt, wenn Sie einen Instanztyp C5, M5 oder R5 verwenden und Ihre eigene Lizenz mitbringen. Von diesen 24 Storage-VMs können bis zu 12 für die Disaster Recovery (DR) konfiguriert werden.

Das Limit kann je nach dem verwendeten EC2 Instanztyp niedriger sein.

Für jede zusätzliche _datenserverdienstende_ Storage-VM über die erste Storage-VM hinaus, die standardmäßig mit Cloud Volumes ONTAP geliefert wird, ist eine Add-on-Lizenz erforderlich. Wenden Sie sich an Ihr Account-Team, um eine SVM-Add-on-Lizenz zu erhalten.

Storage VMs, die Sie für die Disaster Recovery (DR) konfigurieren, erfordern keine zusätzliche Lizenz (sie sind kostenlos), werden aber an die Storage-VM-Grenze angerechnet.

link:reference-limits-aws.html["Erfahren Sie mehr über die Beschränkungen von Storage-VMs"].

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html["Lesen Sie, wie Sie in AWS Daten-Serving-Storage-VMs für Cloud Volumes ONTAP erstellen"^].



=== Zentrale Festplatte für Single-Node-Systeme in AWS

BlueXP weist neuen 9.8 Single Node-Implementierungen in AWS nun eine Core-Festplatte zu, wenn Sie einen Instanztyp C5, M5 oder R5 verwenden. Die Kernfestplatte bietet mehr Möglichkeiten, zwischen unterstützten Instanztypen zu wechseln, erweitert die Fähigkeit des Systems, Kerndateien bei Problemen zu sammeln, und unterstützt künftig größere Instanztypen.

Die Core-Festplatte ist eine General Purpose SSD (gp2) mit 540 gib.


NOTE: Zudem werden jetzt auf Single-Node-Systemen, die diese Instanztypen nutzen, eine Festplatte mit weniger Datenfestplatten unterstützt. link:reference-limits-aws.html["Erfahren Sie mehr über Storage-Limits in AWS"].



== Erforderliche Version des BlueXP Connectors

Der BlueXP-Connector muss Version 3.9.0 oder höher ausführen, um neue Cloud Volumes ONTAP 9.8-Systeme bereitzustellen und bestehende Systeme auf Version 9.8 zu aktualisieren.



== Upgrade-Hinweise

* Upgrades von Cloud Volumes ONTAP müssen von BlueXP abgeschlossen werden. Sie sollten kein Cloud Volumes ONTAP-Upgrade mit System Manager oder der CLI durchführen. Dies kann die Stabilität des Systems beeinträchtigen.
* Sie können ein Upgrade von Version 9.7 auf Cloud Volumes ONTAP 9.8 durchführen. BlueXP fordert Sie auf, Ihre vorhandenen Cloud Volumes ONTAP 9.7-Systeme auf Version 9.8 zu aktualisieren.
+
http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Erfahren Sie, wie Sie aktualisiert werden können, wenn Sie von BlueXP benachrichtigt werden"^].

* Das Upgrade eines einzelnen Node-Systems nimmt das System für bis zu 25 Minuten offline, während dieser I/O-Unterbrechung erfolgt.
* Das Upgrade eines HA-Paars erfolgt unterbrechungsfrei und die I/O wird unterbrochen. Während dieses unterbrechungsfreien Upgrade-Prozesses wird jeder Node entsprechend aktualisiert, um den I/O-Datenverkehr für die Clients weiterhin bereitzustellen.
* In AWS werden die EC2-Instanztypen c4, m4 und R4 von neuen Cloud Volumes ONTAP-Implementierungen nicht mehr unterstützt. Wenn Sie ein System besitzen, das auf einem Instanztyp c4, m4 oder r4 ausgeführt wird, müssen Sie in der instanzfamilie c5, m5 oder r5 zu einem Instanztyp wechseln. Wenn Sie den Instanztyp nicht ändern können, müssen Sie vor dem Upgrade die erweiterte Netzwerkumgebung aktivieren.
+
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["Erfahren Sie, wie Sie ein Upgrade in AWS mit EC2-Instanztypen c4, m4 und R4 durchführen."]
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Erfahren Sie, wie Sie den EC2 Instanztyp für Cloud Volumes ONTAP ändern"^].

+
Siehe link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp Support"^] Hier erhalten Sie weitere Informationen über das Ende der Verfügbarkeit und die Unterstützung dieser Instanztypen.


